export enum ModuleNotification {
  DRIVING_TIME_REQUEST = 'DRIVING_TIME_REQUEST',
  DRIVING_TIME_SUCCESS_RESPONSE = 'DRIVING_TIME_SUCCESS_RESPONSE',
  DRIVING_TIME_FAILED_RESPONSE = 'DRIVING_TIME_FAILED_RESPONSE'
}
